kind: Service
apiVersion: v1
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
        version: v1
    spec:
      containers:
      - name: petclinic
        image: petclinic
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
